# DEPENDABOT TEMPORARILY DISABLED FOR CI/CD TESTING
# Uncomment the sections below to re-enable Dependabot

version: 2
updates: []
  # # Enable version updates for npm
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   reviewers:
  #     - "OdedShaoulian"
  #   assignees:
  #     - "OdedShaoulian"

  # # Enable version updates for npm in server directory
  # - package-ecosystem: "npm"
  #   directory: "/server"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   reviewers:
  #     - "OdedShaoulian"
  #   assignees:
  #     - "OdedShaoulian"

  # # Enable version updates for npm in client directory
  # - package-ecosystem: "npm"
  #   directory: "/client"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   reviewers:
  #     - "OdedShaoulian"
  #   assignees:
  #     - "OdedShaoulian"

  # # Enable version updates for GitHub Actions
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   reviewers:
  #     - "OdedShaoulian"
  #   assignees:
  #     - "OdedShaoulian"
